FROM node:12-alpine
RUN apk add git
WORKDIR /app
RUN git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
WORKDIR /app/NeteaseCloudMusicApi
RUN npm config set registry https://registry.npm.taobao.org 
RUN npm install
CMD [ "node", "app.js" ]