version: "3.7"

services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: music_api
    ports: 
      - "3000:3000"
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: music_app
    links: 
      - api:api
    working_dir: /app
    volumes: 
      - './:/app'
      - '/app/node_modules'
    ports: 
      - "9999:9999"
    command: npm run dev
      